version: '3'
services:
  api:
    image: podnoms.azurecr.io/podnoms.api
    container_name: ${API_CONTAINER_NAME:-api}
    environment:
      VIRTUAL_HOST: ${API_DOMAINS}
      LETSENCRYPT_HOST: ${API_DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      ASPNETCORE_URLS: http://0.0.0.0:80
  web:
    image: podnoms.azurecr.io/podnoms.web
    container_name: ${WEB_CONTAINER_NAME:-web}
    restart: always
    environment:
      VIRTUAL_HOST: ${WEB_DOMAINS}
      LETSENCRYPT_HOST: ${WEB_DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
  orchestra:
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/containers/portainer/data:/data
    environment:
      VIRTUAL_HOST: ${ORCHESTRATOR_DOMAINS}
      LETSENCRYPT_HOST: ${ORCHESTRATOR_DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
  # watchtower:
  #   image: v2tec/watchtower
  #   container_name: podnoms.watcher
  #       restart: always
  #       environment:
  #           - REPO_USER=${REPO_USER}
  #           - REPO_PASS=${REPO_PASS}
  #           - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS}
  #           - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL}
  #           - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=${WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER}
  #       volumes:
  #           - /var/run/docker.sock:/var/run/docker.sock
  #       command: --interval 30 --label-enable

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
